name: Deploy Flask App to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Github Repository의 소스 코드를 불러옵니다.
      - name: Checkout source code
        uses: actions/checkout@v4

      # 2. Python 3.9 버전을 설치합니다.
      - name: Setup 3.11-slim
        uses: actions/setup-python@v5

      # 3. .env 파일을 생성합니다. (Flask 설정값)
      # Github Secrets에 DOT_ENV 라는 이름으로 .env 파일 내용을 등록해야 합니다.
#      - name: Create .env file
#        run: echo "${{ secrets.DOT_ENV }}" > ./.env

      # 4. AWS Resource에 접근할 수 있게 AWS credentials을 설정합니다.
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-northeast-2
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      # 5. AWS ECR에 로그인합니다.
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # 6. Docker 이미지를 빌드합니다. (Dockerfile이 프로젝트 루트에 있어야 합니다)
      - name: Build Docker image
        run: docker build -t my-flask-app .

      # 7. 빌드한 Docker 이미지에 ECR 주소로 태그를 지정합니다.
      - name: Tag Docker image
        run: docker tag my-flask-app ${{ steps.login-ecr.outputs.registry }}/my-flask-app:latest

      # 8. ECR에 Docker 이미지를 Push합니다.
      - name: Push Docker image to ECR
        run: docker push ${{ steps.login-ecr.outputs.registry }}/my-flask-app:latest

      # 9. SSH로 EC2에 접속하여 배포 스크립트를 실행합니다.
      - name: Deploy to EC2 instance
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script_stop: true
          script: |
#            EC2 서버에 .env 파일 생성
#            echo "${{ secrets.DOT_ENV }}" > .env
            
            # 기존 컨테이너 중지 및 삭제
            docker stop my-flask-app || true
            docker rm my-flask-app || true
            
            # ECR에서 최신 이미지 pull
            docker pull ${{ steps.login-ecr.outputs.registry }}/my-flask-app:latest
            
            # 새 컨테이너 실행 (80 포트로 접속 시 컨테이너의 5000 포트로 연결)
            # --env-file 옵션으로 .env 파일의 환경변수를 컨테이너에 주입
            docker run -d --env-file .env --name my-flask-app -p 80:5000 ${{ steps.login-ecr.outputs.registry }}/my-flask-app:latest